## RanchPal
# Machine Learning internship

# Done by **Palak** Dhingra

Write a python code to import sample-data.csv file as attached and do the following operations on it: 

1. Add a column in last which has converted time in local-time in Format YY/MM/DD HH:MM:SS from epoch time in column. 

2. Add a column in last which will add labels in specific cells in the column. It will ask at runtime to input cell numbers and Label to add in specific cells. 

Labels will INT i.e. 1, 2, 3, 4 upto 9 (just one digit)

cell number will be row number to input in range i.e. 1st value ex. 750 to 2nd value ex.5765 
Example: labels entered is let us 2 and same to labelled in cell from row no. 705 to row no. 5765. 

Please submit your own work only latest on 1st Jun21 by 4 pm . If found to have taken any type of external help will be rejected.

In [ ]:
import pandas as pd
import numpy as np
import time

In [ ]:
df = pd.read_csv('/content/sample-data.csv')

In [ ]:
df

             time      accX      accY  ...      magX      magY      magZ
0      1620022010 -5.509766 -2.220703  ... -0.175195  0.006348  0.060303
1      1620022010 -5.533203 -2.210938  ... -0.175195  0.006348  0.060303
2      1620022010 -5.591797 -2.097656  ... -0.175195  0.006348  0.060303
3      1620022011 -5.517578 -2.107422  ... -0.175195  0.006348  0.060303
4      1620022011 -5.562500 -2.152344  ... -0.175195  0.006348  0.060303
...           ...       ...       ...  ...       ...       ...       ...
10450  1620022189 -6.326172 -1.777344  ... -0.175195  0.006348  0.060303
10451  1620022189 -6.398438 -1.783203  ... -0.175195  0.006348  0.060303
10452  1620022189 -6.392578 -1.792969  ... -0.175195  0.006348  0.060303
10453  1620022189 -6.388672 -1.783203  ... -0.175195  0.006348  0.060303
10454  1620022189 -6.404297 -1.738281  ... -0.175195  0.006348  0.060303

[10455 rows x 10 columns]

In [60]:
df1=df['time']

In [61]:
df1

0        1620022010
1        1620022010
2        1620022010
3        1620022011
4        1620022011
            ...
10450    1620022189
10451    1620022189
10452    1620022189
10453    1620022189
10454    1620022189
Name: time, Length: 10455, dtype: int64

# CONVERTING TIME INTO DESIRED FORMAT

In [63]:
final=[]
for x in range (len(df['time'])):
  y=df1[x]
  a=time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(y))
  b=a[2:19]
  final.append(b)

In [112]:
final

['21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:50',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:51',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:52',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:53',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:54',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:55',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:56',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:57',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:58',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:06:59',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:00',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:01',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:02',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:03',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:04',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:06',
 '21-05-03 06:07:06',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:05',
 '21-05-03 06:07:06',

In [70]:
len(final)

10455

In [71]:
df['Final time']= final

In [72]:
df

             time      accX      accY  ...      magY      magZ         Final time
0      1620022010 -5.509766 -2.220703  ...  0.006348  0.060303  21-05-03 06:06:50
1      1620022010 -5.533203 -2.210938  ...  0.006348  0.060303  21-05-03 06:06:50
2      1620022010 -5.591797 -2.097656  ...  0.006348  0.060303  21-05-03 06:06:50
3      1620022011 -5.517578 -2.107422  ...  0.006348  0.060303  21-05-03 06:06:51
4      1620022011 -5.562500 -2.152344  ...  0.006348  0.060303  21-05-03 06:06:51
...           ...       ...       ...  ...       ...       ...                ...
10450  1620022189 -6.326172 -1.777344  ...  0.006348  0.060303  21-05-03 06:09:49
10451  1620022189 -6.398438 -1.783203  ...  0.006348  0.060303  21-05-03 06:09:49
10452  1620022189 -6.392578 -1.792969  ...  0.006348  0.060303  21-05-03 06:09:49
10453  1620022189 -6.388672 -1.783203  ...  0.006348  0.060303  21-05-03 06:09:49
10454  1620022189 -6.404297 -1.738281  ...  0.006348  0.060303  21-05-03 06:09:49

[10455 rows x 11 columns]

# ADDING LABELS

In [102]:
empty_list=[0]*10455

In [103]:
df['Labels']=empty_list

In [104]:
df.head()

         time      accX      accY  ...      magZ         Final time  Labels
0  1620022010 -5.509766 -2.220703  ...  0.060303  21-05-03 06:06:50       0
1  1620022010 -5.533203 -2.210938  ...  0.060303  21-05-03 06:06:50       0
2  1620022010 -5.591797 -2.097656  ...  0.060303  21-05-03 06:06:50       0
3  1620022011 -5.517578 -2.107422  ...  0.060303  21-05-03 06:06:51       0
4  1620022011 -5.562500 -2.152344  ...  0.060303  21-05-03 06:06:51       0

[5 rows x 12 columns]

In [105]:
df2=df['Labels']

Enter label value
10
INVALID

In [120]:
start=int(input(print("Enter starting column value")))
if start<0 or start>10454:
  print("INVALID ")
end=int(input(print("Enter ending column value")))
if end<1 or end>10455:
  print("INVALID ")
label=int(input(print("Enter label value")))
if label<1 or label>9:
  print("INVALID ")

Enter starting column value
2
Enter ending column value
5
Enter label value
6

In [121]:
for i in range (start,end):
  df2[i]=label

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [122]:
df2

0        0
1        0
2        6
3        6
4        6
        ..
10450    0
10451    0
10452    0
10453    0
10454    0
Name: Labels, Length: 10455, dtype: int64

In [123]:
df

             time      accX      accY  ...      magZ         Final time  Labels
0      1620022010 -5.509766 -2.220703  ...  0.060303  21-05-03 06:06:50       0
1      1620022010 -5.533203 -2.210938  ...  0.060303  21-05-03 06:06:50       0
2      1620022010 -5.591797 -2.097656  ...  0.060303  21-05-03 06:06:50       6
3      1620022011 -5.517578 -2.107422  ...  0.060303  21-05-03 06:06:51       6
4      1620022011 -5.562500 -2.152344  ...  0.060303  21-05-03 06:06:51       6
...           ...       ...       ...  ...       ...                ...     ...
10450  1620022189 -6.326172 -1.777344  ...  0.060303  21-05-03 06:09:49       0
10451  1620022189 -6.398438 -1.783203  ...  0.060303  21-05-03 06:09:49       0
10452  1620022189 -6.392578 -1.792969  ...  0.060303  21-05-03 06:09:49       0
10453  1620022189 -6.388672 -1.783203  ...  0.060303  21-05-03 06:09:49       0
10454  1620022189 -6.404297 -1.738281  ...  0.060303  21-05-03 06:09:49       0

[10455 rows x 12 columns]